#!/bin/bash

set -e

RELEASES_URL="https://github.com/metafates/mangal/releases"
FILE_BASENAME="mangal"

test -z "$VERSION" && VERSION="$(curl -sfL -o /dev/null -w "%{url_effective}" "$RELEASES_URL/latest" |
  rev |
  cut -f1 -d'/' |
  rev)"

test -z "$VERSION" && {
  echo "Unable to get mangal version." >&2
  exit 1
}

test -z "$TMPDIR" && TMPDIR="$(mktemp -d)"



TAR_NAME="${FILE_BASENAME}_${VERSION:1}_$(uname -s)_$(uname -m).tar.gz"
TAR_FILE="$TMPDIR/${TAR_NAME}"

export TAR_NAME
export TAR_FILE

(
  cd "$TMPDIR"
  echo "Downloading Mangal $VERSION..."
  curl -sfLo "$TAR_FILE" \
    "$RELEASES_URL/download/$VERSION/${TAR_NAME}"

  echo "Downloading checksums..."
  curl -sfLo "checksums.txt" "$RELEASES_URL/download/$VERSION/checksums.txt"

  echo "Verifying checksums..."
  if command -v sha256sum &>/dev/null; then
    sha256sum --ignore-missing --quiet --check checksums.txt
  else
    shasum -a 256 --ignore-missing --quiet --check checksums.txt
  fi
)

tar -xf "$TAR_FILE" -C "$TMPDIR"

echo "Installing..."
case $(uname) in
Darwin)
  echo "macOS detected. Checking if brew is installed..."
  if command -v brew &>/dev/null; then
    OUT="$(brew --prefix)/bin/"
    echo "Brew is installed. Moving to ${OUT}"
    echo "But I would recommend installing it with brew directly"
    cp "${TMPDIR}/${FILE_BASENAME}" "${OUT}"
  else
    OUT="/usr/local/bin/"
    echo "Brew is not installed. Moving to ${OUT}"
    sudo cp "${TMPDIR}/${FILE_BASENAME}" "${OUT}"
  fi
  ;;

*)
  OUT="/usr/local/bin/"
  echo "Linux detected. Moving to ${OUT}"
  sudo cp "${TMPDIR}/${FILE_BASENAME}" "${OUT}"
  ;;
esac

echo "Checking if it's available in the PATH..."
if ! command -v mangal &>/dev/null; then
  echo "Looks like it's not :("

  cp "${TMPDIR}/${FILE_BASENAME}" ./
  echo "I've moved mangal to your current directory, try installing it manually"
  exit 1
fi

echo "Mangal is now installed. You can run this script again to update it"
rm "${TMPDIR}/${FILE_BASENAME}"
exit 0
