name: Bug Report
description: File a bug report
labels: [ "bug" ]
body:
  - type: textarea
    attributes:
      label: Describe the bug
      description: "A clear and concise description of what the bug is."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproduction steps
      description: "Steps to reproduce the behavior"
      placeholder: |
        1. Search for ...
        2. Select ...
        3. Do something else
        4. See error
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected behavior
      description: "A clear and concise description of what you expected to happen."
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context
      description: "Add any other context about the problem here."
    validations:
      required: false
  - type: dropdown
    attributes:
      label: "Operating System"
      description: "Which operating system are you using?"
      options:
        - macOS
        - Windows
        - Linux
        - Termux
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        **Thank you for making this app better! ✨**
