// Code generated by "enumer -type=Mode -trimprefix=Mode -json -yaml -text"; DO NOT EDIT.

package config

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _ModeName = "TUIWebScript"

var _ModeIndex = [...]uint8{0, 3, 6, 12}

const _ModeLowerName = "tuiwebscript"

func (i Mode) String() string {
	i -= 1
	if i >= Mode(len(_ModeIndex)-1) {
		return fmt.Sprintf("Mode(%d)", i+1)
	}
	return _ModeName[_ModeIndex[i]:_ModeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ModeNoOp() {
	var x [1]struct{}
	_ = x[ModeTUI-(1)]
	_ = x[ModeWeb-(2)]
	_ = x[ModeScript-(3)]
}

var _ModeValues = []Mode{ModeTUI, ModeWeb, ModeScript}

var _ModeNameToValueMap = map[string]Mode{
	_ModeName[0:3]:       ModeTUI,
	_ModeLowerName[0:3]:  ModeTUI,
	_ModeName[3:6]:       ModeWeb,
	_ModeLowerName[3:6]:  ModeWeb,
	_ModeName[6:12]:      ModeScript,
	_ModeLowerName[6:12]: ModeScript,
}

var _ModeNames = []string{
	_ModeName[0:3],
	_ModeName[3:6],
	_ModeName[6:12],
}

// ModeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ModeString(s string) (Mode, error) {
	if val, ok := _ModeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ModeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Mode values", s)
}

// ModeValues returns all values of the enum
func ModeValues() []Mode {
	return _ModeValues
}

// ModeStrings returns a slice of all String values of the enum
func ModeStrings() []string {
	strs := make([]string, len(_ModeNames))
	copy(strs, _ModeNames)
	return strs
}

// IsAMode returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Mode) IsAMode() bool {
	for _, v := range _ModeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for Mode
func (i Mode) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for Mode
func (i *Mode) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Mode should be a string, got %s", data)
	}

	var err error
	*i, err = ModeString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for Mode
func (i Mode) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for Mode
func (i *Mode) UnmarshalText(text []byte) error {
	var err error
	*i, err = ModeString(string(text))
	return err
}

// MarshalYAML implements a YAML Marshaler for Mode
func (i Mode) MarshalYAML() (interface{}, error) {
	return i.String(), nil
}

// UnmarshalYAML implements a YAML Unmarshaler for Mode
func (i *Mode) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}

	var err error
	*i, err = ModeString(s)
	return err
}
