/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/image": {
    /** @description Get image from URL bypassing CORS policy */
    get: operations["getImage"];
  };
  "/mangalInfo": {
    /** @description Get information about installed Mangal app */
    get: operations["getMangalInfo"];
  };
  "/providers": {
    /** @description Get avaiable providers */
    get: operations["getProviders"];
  };
  "/searchMangas": {
    /** @description search for mangas */
    get: operations["searchMangas"];
  };
  "/mangaVolumes": {
    /** @description get manga volumes */
    get: operations["getMangaVolumes"];
  };
  "/volumeChapters": {
    /** @description get volume chapters */
    get: operations["getVolumeChapters"];
  };
  "/manga": {
    /** @description Get manga */
    get: operations["getManga"];
  };
  "/chapter": {
    /** @description Get chapter */
    get: operations["getChapter"];
  };
  "/provider": {
    /** @description Get provider */
    get: operations["getProvider"];
  };
  "/mangaPage": {
    /** @description Get manga page with volumes and chapters */
    get: operations["getMangaPage"];
  };
  "/formats": {
    /** @description Get avaiable formats */
    get: operations["getFormats"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** Format: binary */
    Image: string;
    Provider: {
      name: string;
      id: string;
      description?: string;
      version: string;
    };
    Manga: {
      id: string;
      title: string;
      url?: string;
      banner?: string;
      cover?: string;
    };
    CoverImage: {
      extraLarge: string;
      large: string;
      medium: string;
      color: string;
    };
    AnilistManga: {
      coverImage: components["schemas"]["CoverImage"];
      bannerImage?: string;
      description?: string;
    };
    Volume: {
      number: number;
    };
    Chapter: {
      title: string;
      /** Format: float */
      number: number;
      url?: string;
    };
    VolumeWithChapters: {
      volume: components["schemas"]["Volume"];
      chapters: components["schemas"]["Chapter"][];
    };
    MangaPage: {
      manga: components["schemas"]["Manga"];
      anilistManga?: components["schemas"]["AnilistManga"];
      volumes: components["schemas"]["VolumeWithChapters"][];
    };
    MangalInfo: {
      version: string;
    };
    Format: {
      name: string;
      extension?: string;
    };
    Error: {
      /** Format: int32 */
      code: number;
      message: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export interface operations {

  /** @description Get image from URL bypassing CORS policy */
  getImage: {
    parameters: {
      query: {
        /** @description image url to download */
        url: string;
        /** @description referer to use to get the image */
        referer?: string;
      };
    };
    responses: {
      /** @description image response */
      200: {
        content: {
          "image/png": components["schemas"]["Image"];
        };
      };
    };
  };
  /** @description Get information about installed Mangal app */
  getMangalInfo: {
    responses: {
      /** @description mangal info response */
      200: {
        content: {
          "application/json": components["schemas"]["MangalInfo"];
        };
      };
      /** @description unexpected error */
      default: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /** @description Get avaiable providers */
  getProviders: {
    responses: {
      /** @description providers response */
      200: {
        content: {
          "application/json": components["schemas"]["Provider"][];
        };
      };
      /** @description unexpected error */
      default: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /** @description search for mangas */
  searchMangas: {
    parameters: {
      query: {
        /** @description provider id to use */
        provider: string;
        /** @description manga search query */
        query: string;
      };
    };
    responses: {
      /** @description search results */
      200: {
        content: {
          "application/json": components["schemas"]["Manga"][];
        };
      };
      /** @description unexpected error */
      default: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /** @description get manga volumes */
  getMangaVolumes: {
    parameters: {
      query: {
        /** @description provider id to use */
        provider: string;
        /** @description manga search query */
        query: string;
        /** @description manga id */
        manga: string;
      };
    };
    responses: {
      /** @description manga volumes */
      200: {
        content: {
          "application/json": components["schemas"]["Volume"][];
        };
      };
      /** @description unexpected error */
      default: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /** @description get volume chapters */
  getVolumeChapters: {
    parameters: {
      query: {
        /** @description provider id to use */
        provider: string;
        /** @description manga search query */
        query: string;
        /** @description manga id */
        manga: string;
        /** @description volume number */
        volume: number;
      };
    };
    responses: {
      /** @description volume chapters */
      200: {
        content: {
          "application/json": components["schemas"]["Chapter"][];
        };
      };
      /** @description unexpected error */
      default: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /** @description Get manga */
  getManga: {
    parameters: {
      query: {
        /** @description provider id to use */
        provider: string;
        /** @description manga search query */
        query: string;
        /** @description manga id */
        manga: string;
      };
    };
    responses: {
      /** @description manga response */
      200: {
        content: {
          "application/json": components["schemas"]["Manga"];
        };
      };
      /** @description manga not found */
      404: {
        content: never;
      };
      /** @description unexpected error */
      default: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /** @description Get chapter */
  getChapter: {
    parameters: {
      query: {
        /** @description provider id to use */
        provider: string;
        /** @description manga search query */
        query: string;
        /** @description manga id */
        manga: string;
        /** @description volume number */
        volume: number;
      };
    };
    responses: {
      /** @description chapter response */
      200: {
        content: {
          "application/json": components["schemas"]["Chapter"];
        };
      };
    };
  };
  /** @description Get provider */
  getProvider: {
    parameters: {
      query: {
        /** @description provider id */
        id: string;
      };
    };
    responses: {
      /** @description provider response */
      200: {
        content: {
          "application/json": components["schemas"]["Provider"];
        };
      };
      /** @description provider not found */
      404: {
        content: never;
      };
    };
  };
  /** @description Get manga page with volumes and chapters */
  getMangaPage: {
    parameters: {
      query: {
        /** @description provider id to use */
        provider: string;
        /** @description manga search query */
        query: string;
        /** @description manga id */
        manga: string;
      };
    };
    responses: {
      /** @description manga page response */
      200: {
        content: {
          "application/json": components["schemas"]["MangaPage"];
        };
      };
      /** @description unexpected error */
      default: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /** @description Get avaiable formats */
  getFormats: {
    responses: {
      /** @description formats response */
      200: {
        content: {
          "application/json": components["schemas"]["Format"][];
        };
      };
    };
  };
}
