/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/image": {
    /** @description Get image from URL bypassing CORS policy */
    get: operations["getImage"];
  };
  "/mangalInfo": {
    /** @description Get information about installed Mangal app */
    get: operations["getMangalInfo"];
  };
  "/providers": {
    /** @description Get avaiable providers */
    get: operations["getProviders"];
  };
  "/searchMangas": {
    /** @description Search for mangas */
    get: operations["searchMangas"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** Format: binary */
    Image: string;
    Provider: {
      name: string;
      id: string;
      description?: string;
      version: string;
    };
    Manga: {
      id: string;
      title: string;
      url?: string;
      banner?: string;
      cover?: string;
    };
    MangalInfo: {
      version: string;
    };
    Error: {
      /** Format: int32 */
      code: number;
      message: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export interface operations {

  /** @description Get image from URL bypassing CORS policy */
  getImage: {
    parameters: {
      query: {
        /** @description image url to download */
        url: string;
        /** @description referer to use to get the image */
        referer?: string;
      };
    };
    responses: {
      /** @description image response */
      200: {
        content: {
          "image/png": components["schemas"]["Image"];
        };
      };
    };
  };
  /** @description Get information about installed Mangal app */
  getMangalInfo: {
    responses: {
      /** @description mangal info response */
      200: {
        content: {
          "application/json": components["schemas"]["MangalInfo"];
        };
      };
      /** @description unexpected error */
      default: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /** @description Get avaiable providers */
  getProviders: {
    responses: {
      /** @description providers response */
      200: {
        content: {
          "application/json": components["schemas"]["Provider"][];
        };
      };
      /** @description unexpected error */
      default: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /** @description Search for mangas */
  searchMangas: {
    parameters: {
      query: {
        /** @description provider id to use */
        provider: string;
        /** @description manga search query */
        query: string;
      };
    };
    responses: {
      /** @description search results */
      200: {
        content: {
          "application/json": components["schemas"]["Manga"][];
        };
      };
      /** @description unexpected error */
      default: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
}
