/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/providers": {
    /** @description Get avaiable providers */
    get: operations["getProviders"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    Provider: {
      name?: string;
      id: string;
    };
    Error: {
      /** Format: int32 */
      code: number;
      message: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export interface operations {

  /** @description Get avaiable providers */
  getProviders: {
    responses: {
      /** @description providers response */
      200: {
        content: {
          "application/json": components["schemas"]["Provider"][];
        };
      };
      /** @description unexpected error */
      default: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
}
