// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.13.4 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /mangalInfo)
	GetMangalInfo(ctx echo.Context) error

	// (GET /providers)
	GetProviders(ctx echo.Context) error

	// (GET /searchMangas)
	SearchMangas(ctx echo.Context, params SearchMangasParams) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetMangalInfo converts echo context to params.
func (w *ServerInterfaceWrapper) GetMangalInfo(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetMangalInfo(ctx)
	return err
}

// GetProviders converts echo context to params.
func (w *ServerInterfaceWrapper) GetProviders(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetProviders(ctx)
	return err
}

// SearchMangas converts echo context to params.
func (w *ServerInterfaceWrapper) SearchMangas(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchMangasParams
	// ------------- Required query parameter "provider-id" -------------

	err = runtime.BindQueryParameter("form", true, true, "provider-id", ctx.QueryParams(), &params.ProviderId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter provider-id: %s", err))
	}

	// ------------- Required query parameter "query" -------------

	err = runtime.BindQueryParameter("form", true, true, "query", ctx.QueryParams(), &params.Query)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter query: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SearchMangas(ctx, params)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/mangalInfo", wrapper.GetMangalInfo)
	router.GET(baseURL+"/providers", wrapper.GetProviders)
	router.GET(baseURL+"/searchMangas", wrapper.SearchMangas)

}

type GetMangalInfoRequestObject struct {
}

type GetMangalInfoResponseObject interface {
	VisitGetMangalInfoResponse(w http.ResponseWriter) error
}

type GetMangalInfo200JSONResponse MangalInfo

func (response GetMangalInfo200JSONResponse) VisitGetMangalInfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetMangalInfodefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GetMangalInfodefaultJSONResponse) VisitGetMangalInfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetProvidersRequestObject struct {
}

type GetProvidersResponseObject interface {
	VisitGetProvidersResponse(w http.ResponseWriter) error
}

type GetProviders200JSONResponse []Provider

func (response GetProviders200JSONResponse) VisitGetProvidersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetProvidersdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GetProvidersdefaultJSONResponse) VisitGetProvidersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type SearchMangasRequestObject struct {
	Params SearchMangasParams
}

type SearchMangasResponseObject interface {
	VisitSearchMangasResponse(w http.ResponseWriter) error
}

type SearchMangas200JSONResponse []Manga

func (response SearchMangas200JSONResponse) VisitSearchMangasResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type SearchMangasdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response SearchMangasdefaultJSONResponse) VisitSearchMangasResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (GET /mangalInfo)
	GetMangalInfo(ctx context.Context, request GetMangalInfoRequestObject) (GetMangalInfoResponseObject, error)

	// (GET /providers)
	GetProviders(ctx context.Context, request GetProvidersRequestObject) (GetProvidersResponseObject, error)

	// (GET /searchMangas)
	SearchMangas(ctx context.Context, request SearchMangasRequestObject) (SearchMangasResponseObject, error)
}

type StrictHandlerFunc = runtime.StrictEchoHandlerFunc
type StrictMiddlewareFunc = runtime.StrictEchoMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// GetMangalInfo operation middleware
func (sh *strictHandler) GetMangalInfo(ctx echo.Context) error {
	var request GetMangalInfoRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetMangalInfo(ctx.Request().Context(), request.(GetMangalInfoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMangalInfo")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetMangalInfoResponseObject); ok {
		return validResponse.VisitGetMangalInfoResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("Unexpected response type: %T", response)
	}
	return nil
}

// GetProviders operation middleware
func (sh *strictHandler) GetProviders(ctx echo.Context) error {
	var request GetProvidersRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetProviders(ctx.Request().Context(), request.(GetProvidersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetProviders")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetProvidersResponseObject); ok {
		return validResponse.VisitGetProvidersResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("Unexpected response type: %T", response)
	}
	return nil
}

// SearchMangas operation middleware
func (sh *strictHandler) SearchMangas(ctx echo.Context, params SearchMangasParams) error {
	var request SearchMangasRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.SearchMangas(ctx.Request().Context(), request.(SearchMangasRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SearchMangas")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(SearchMangasResponseObject); ok {
		return validResponse.VisitSearchMangasResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("Unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xVQW7bMBD8CrHtUY3c5OZjgaDwoUCAoOghzWEtrm0GEsksV0YNQ38vSEqyU8uNgRZt",
	"TpLo0czOcETvoXKNd5asBJjvIVQbajDd3jI7jjeenScWQ2m5cprideW4QYE5GCs311CA7DzlR1oTQ1dA",
	"QyHgOqH7H4OwsWvougKYnlvDpGH+kDkP+MeRzC2fqJLI9QXtGk+nESP1BQIZdpa3XtiVOyXfEgfj7Ov0",
	"A3BK4I7d1miaSNLoCeYCLDYXODJ6Qi2CTG+lT6Y3qL7dflJfF1AcTMHHq9nVLCo6Txa9gTncpKUCPMom",
	"zVg2L/JZk8SLplCx8ZJ5PpOoqBr7YJxVuHRtXAmCdU1a9ROg95C0OMEWOr96tAHRYfDOhpzP9WyWC2eF",
	"bNJF72tTpdfLp5B3Jjc23r1nWsEc3pWHSpd9n8sjlZTSSwfZZDKhhhEgoVbY1vLXpsif1MQAraUfnioh",
	"rWjAdAWUvi9P+G34uEWDy5rUCP9up6K+G9n+MGkj1ITXzI7F78aeIjPupvyPg7+t+AMhV5vUnfM7cJ9A",
	"auVYNRn5a/T3xzTx42JsSNKuPuzPJKHEqTbEU9HE5eeWeAfD4TCiPhgNx+eCcEvFURonZ8h+qvkq+1SD",
	"yJTi8Hi51uO/KFn+W7igYb1FptDWEv5/u7ruZwAAAP//kYKQfXsHAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
