// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.13.4 DO NOT EDIT.
package api

// Error defines model for Error.
type Error struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

// Provider defines model for Provider.
type Provider struct {
	Id   string  `json:"id"`
	Name *string `json:"name,omitempty"`
}
